### ISSUE TITLE
Automated Test for Sample 04.1 (File Transfer Listener)

### ISSUE THREAD

**Issue by pkirch** [eclipse-edc/Connector#1535] opened 2022-06-23 15:43 UTC
# Feature Request

Add automated integration tests that run in CI for samples to prevent the
samples breaking due to changes in the EDC.

The scope of this story is to add automated integration tests for sample 04.1 (file transfer listener).

## Which Areas Would Be Affected?

CI, samples

## Why Is the Feature Desired?

- Prevent the samples breaking due to changes in the EDC.
- Ensure samples can be followed as described.

## Solution Proposal

Provide an integration test using Rest Assured which is aligned to the steps of
the sample readme.

Related issue and analog solution: #1269

## Type of Issue

testing / reliability

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment] 2022-06-24 06:51
Duplicate of #1269 , please close one of the two issues adding the `duplicate` label

**Comment by pkirch** [comment] 2022-06-24 07:22
> Duplicate of #1269 , please close one of the two issues adding the `duplicate` label

In order to keep the issues open only for a reasonable time and to have the possibility to have focused discussions each sample gets its own issue.

#1269 is for sample 4.0
this one is for 4.1

Makes sense?

**Comment by ndr-brt** [comment] 2022-06-24 07:31
I didn't notice the difference in the sample number, sorry, yes, it's reasonable.

**Closed as completed** 2022-07-11 12:58 UTC
