### ISSUE TITLE
Consistent datasource configuration resolution

### ISSUE THREAD

**Issue by benhid** [eclipse-edc/Connector#4648] opened 2024-11-27 10:05 UTC
# Feature Request

## Which Areas Would Be Affected?

`sql-pool`, `sql-bootstrapper` extensions

## Why Is the Feature Desired?

Currently, there is a contradictory behavior in how data source configurations are resolved:

If the data source URL is defined in the properties file, `sql-pool` logs a [warning](https://github.com/eclipse-edc/Connector/blob/9cdf67bd5d64c5bd8b0de3b5a9a46fa0a9762f39/extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java#L130):

> consumer  | WARNING 2024-11-27T07:10:56.935880255 Datasource configuration value 'edc.datasource.default.url' not found in vault, will fall back to Config. Please consider putting datasource configuration into the vault.  

However, when the data source URL is removed from the properties file and added to the vault, `sql-bootstrapped` [fails](https://github.com/eclipse-edc/Connector/blob/9cdf67bd5d64c5bd8b0de3b5a9a46fa0a9762f39/extensions/common/sql/sql-bootstrapper/src/main/java/org/eclipse/edc/sql/bootstrapper/SqlDmlStatementRunner.java#L78) with the following error:

> consumer  | SEVERE 2024-11-27T07:49:43.381508988 Error booting runtime: Failed to bootstrap SQL schema, error 'No datasource found with name 'default''  
> consumer  | org.eclipse.edc.spi.persistence.EdcPersistenceException: Failed to bootstrap SQL schema, error 'No datasource found with name 'default''  
> consumer  |     at org.eclipse.edc.sql.bootstrapper.SqlSchemaBootstrapperExtension.lambda$prepare$0(SqlSchemaBootstrapperExtension.java:58)  

This creates a "conflict" between the two extensions.

## Solution Proposal

Both the SQL dependency and the bootstrapper should prioritize the vault as the primary source for configuration.

**Comment by paullatzelsperger** [comment] 2024-11-27 10:10
the SQL bootstrapper is **not** intended for production installations, it is a mere convenience feature to avoid having to create DB schemas manually, thus it shouldn't be expected to be on par with the SQL pool impl. 

However, feel free to submit a PR that adds the "vault-or-config" mechanism into the bootstrapper :) (read or [contribution guidelines](https://eclipse-edc.github.io/documentation/for-contributors/guidelines/#how-to-contribute) first though).

**Comment by benhid** [comment] 2024-11-27 12:25
I wasn’t aware that it wasn't designed for production use. If this is documented somewhere, I may have overlooked it.

That said, I still believe that aligning the configuration resolution logic between the SQL bootstrapper and the SQL pool implementation would significantly improve the developer experience. 

I appreciate the invitation to contribute :-) I’ll review the contribution guidelines and consider submitting a PR to implement the mechanism in the bootstrapper.

Thanks!

**Comment by paullatzelsperger** [comment] 2024-11-27 12:55
while it is perfectly usable in demo/test/dev scenarios, the bootstrapper is severely limited in its practical applicability for production use, for example, it only does schema generation, no data migration. In clustered scenarios, one would also have to consider simultaneous read- and write access to a database.

These limitations are by design, because we think that it is not EDC's core competency to solve this problem on a generic level. Tools like Flyway and Liquibase exist, but larger companies tend to have specialist departments.

**Comment by paullatzelsperger** [comment] 2024-11-27 13:28
@benhid actually, I did take a closer look at this, and in fact, the SQL bootstrapper doesn't create the datasource itself, instead it uses the same facility that all the SQL stores use. 

In other words, i was perfectly able to store the Postgres connection stuff in the vault, and still use the bootstrapper. 

Note that I did add a configuration value `edc.datasource.default.name=default` so that it gets picked up.

Can you confirm this?

**Comment by benhid** [comment] 2024-11-28 07:28
Thank you for the clarification!

I’ve tested this again following your suggestion, and indeed, it works when adding `edc.datasource.default.name=default`. Interestingly, it also works with variations like `edc.datasource.default.name=other` or even `edc.datasource.default.foo=default`.

Looking at the code, it seems that the [datasource is created](https://github.com/eclipse-edc/Connector/blob/8c49531cf645adc59dcba4d3adece55576114c5d/extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java#L110-L115) whenever a configuration key with the `edc.datasource.<context>` prefix exists, regardless of the specific property name that follows. The logic first checks for `edc.datasource.<context>.url` in the vault, and if it’s not found, it falls back to the application properties.

This behavior feels a bit confusing. I would have expected that if the `edc.datasource.<context>.url` property exists in the application properties, its value would be interpreted as the key of the secret to be retrieved from the vault. Otherwise, it would fall back to using the full configuration directly (similar to how the `edc.api.auth.key.alias` key is handled in the [`auth-tokenbased`](https://github.com/eclipse-edc/Connector/blob/8c49531cf645adc59dcba4d3adece55576114c5d/extensions/common/auth/auth-tokenbased/README.md#token-based-authentication-service) extension, or how credentials are handled in the [`aws-s3-core`](https://github.com/eclipse-edc/Technology-Aws/tree/main/extensions/common/aws/aws-s3-core#s3-core) extension).

Do you think this adjustment would make sense? Overall, I feel like the vault lookup logic could be more consistent across the different extensions (maybe documented in a common place?), but I understand that this might be a more significant change. 

Thanks again for your time and support!

**Comment by paullatzelsperger** [comment] 2024-11-28 09:33
Yes, you are correct, the lookup is triggered based on the presence the key prefix `edc.datasource`, regardless of the key.

Actually, `edc.api.auth.key.alias` is deprecated, and the behaviour there is different: 
- if `edc.api.auth.key.alias` is set, use it, and attempt to resolve the secret
- if not, use `edc.api.auth.key` and resolve the string from config.
so as you can see these two individual properties.

I think there could indeed be value in employing a consistent scheme like that for sensitive properties: for any sensitive value, use the `x.y.z.alias` property as secret alias to resolve from the vault, and if that is not configured, use the `x.y.z` property for the value. This would not work for _all_ sensitive values, e.g. access credentials for the vault can't be stored in the vault, obviously.

Specifically, for the PostgreSQL values this would mean:
- `edc.datasource.default.url.alias` contains the vault alias for the entry that contains the URL, and `edc.datasource.default.url` contains the url directly
- `edc.datasource.default.username.alias` contains the vault alias for the entry that contains the username, and `edc.datasource.default.username` contains the username directly
- and so forth

Here's how we'll proceed: if you can open a discussion in the "Ideas" section about this, we (the committers) will discuss it in one of the upcoming triage meetings and, pending approval, an issue can be created. We'll also have to consider things like backwards compatibility.

**Comment by paullatzelsperger** [comment] 2024-12-04 08:21
i'll close this issue, because a more focused discussion #4649 (and subsequent issue) supersedes it.

**Closed by paullatzelsperger** 2024-12-04 08:21 UTC
Labels: feature_request
