### ISSUE TITLE
Transformers set `DATASPACE_PROTOCOL_HTTP`

### ISSUE THREAD

**Issue by jimmarino** [eclipse-edc/Connector#2922] opened 2023-05-09 14:28 UTC
Currently, many of the DSP transformers set the protocol on the emitted message to `DATASPACE_PROTOCOL_HTTP.` This should not be done as they are independent of the transport protocol.

**Comment by juliapampus** [comment] 2023-05-10 07:08
Duplicate of #2775

**Closed** 2023-05-10 21:01 UTC
Labels: enhancement
