### ISSUE TITLE
Jsonld files are not registered (Windows only)

### ISSUE THREAD

**Issue by stefan1207** [eclipse-edc/Connector#4219] opened 2024-05-28 10:45 UTC
# Bug Report

## Describe the Bug

When starting EDC with Windows, lson ld files are not registered. Log files read:

```
INFO 2024-05-28T12:02:01.6806667 Initialized JSON-LD Extension
WARNING 2024-05-28T12:39:12.9628396 Failed to register cached json-ld document: Cannot find resource document\odrl.jsonld
WARNING 2024-05-28T12:39:12.966752 Failed to register cached json-ld document: Cannot find resource document\dspace.jsonld
```

Later when trying to create a policy, an error message is shown (return code 400):

`Caused by: JsonLdError[code=The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED]., message=URL scheme [http] is not supported.]
`
### Expected Behavior

Warning does not appear. Creating policy is possible.

### Observed Behavior

See description

## Steps to Reproduce

Just start a EDC connector (e.g. Sample project for simple transfer) with Windows.

## Context Information

EDC 0.7.0, Windows 10

## Possible Implementation

I found the root cause already: 

In  ([org.eclipse.edc.jsonld.JsonLdExtension:96](https://github.com/eclipse-edc/Connector/blob/7b022912d45a8537c2d39cf07de0c8464d945274/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java#L96))

`).forEach(jsonLdContext -> getResourceUri("document" + **File.separator** + jsonLdContext.fileName())
`

"File.separator" must not be used. Its backslash for Windows. Uri need to have "/" only.

Furthermore there is a syntax error in [dspace.jsonld](https://github.com/eclipse-edc/Connector/blob/7b022912d45a8537c2d39cf07de0c8464d945274/extensions/common/json-ld/src/main/resources/document/dspace.jsonld#L58):

`Invalid token=STRING at (line no=59, column no=19, offset=2480). Expected tokens are: [COMMA]
`

**Comment by paullatzelsperger** [comment] 2024-05-28 11:07
We are aware of this situation, but there are a few things to consider: 
- if we change this, we'll need to add a test to guard against regression. That means, we'd have to run our test suite against a Windows [10/11/?] host. This will significantly expand our CI/CD run times.
- Windows is not the typical platform to run EDC. We are aware, that many devs use Windows, but we typically recommend using WSL. EDC is a backend (or "server") application, and those typically run in a *nix environment.
- Due to the aforementioned reasons, this is not a high priority for us at the moment. 

Apart from that, please at least format your Issue description properly using either backticks or code fences. If you're referencing files or even line numbers it's a good idea to actually add a reference to the file using hyperlinks.

**Comment by stefan1207** [comment] 2024-05-28 11:46
Thank you for your answer. I understand your points.

**Comment by NIdhogg-bug** [comment] 2024-05-29 06:17
How can this issue be resolved? I cannot use EDC-Simple or any other projects. Is this a problem with the EDC code or with JSON-LD itself?It might work with the previous JAR, but the current packaged version encounters this issue.

**Comment by stefan1207** [comment] 2024-05-29 06:25
The problem is that jsonld files do not get registered on startup (see WARNING message in log files as shown in description of this bug). If you use Linux not Windows, then this issue does not occur. For Windows, an option would be implementing a quick fix in a temporarily used extension (as I did now).

**Comment by paullatzelsperger** [comment] 2024-05-29 07:32
we could just fix it (replacing `File.separator` with `/`). However, we won't be adding any tests for that specifically, since Windows is not a supported platform.

**Closed** 2024-05-29 08:53 UTC
Labels: triage
