### ISSUE TITLE
Multiple partitions are not being transfered in Http Datapalne

### ISSUE THREAD

**Issue by git-masoud** [eclipse-edc/Connector#3417] opened 2023-09-06 14:10 UTC
# Bug Report

## Describe the Bug
The HttpDataSink component only transfers the first partition of data when there are multiple partitions.

### Expected Behavior

The HttpDataSink should be able to transfer all partitions of data.

### Observed Behavior

Currently, when multiple partitions are sent to the HttpDataSink, only the first partition is transferred. The others are not transferred.

## Steps to Reproduce

- Use Kafka as the source for an asset.
- Configure HttpData as the target.
   - Note that the default partition size is hard-coded to 5.
- After the Kafka topic receives 5 messages, the transferPart function is triggered, but it only sends the first message to the designated endpoint.

## Possible Implementation

One possible solution to this bug is to remove the "Return Early" condition from the [TransferParts](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java#L51C20-L51C20) function. This will allow the HttpDataSink to process and transfer all partitions of data.

**Comment by ndr-brt** [comment] 2023-09-28 08:29
sorry, I missed this, I tried the same case (through the [`EndToEndKafkaTransferTest`](https://github.com/eclipse-edc/Connector/blob/bbfcbabd564cc4b4bc1d76a7691318203670a80f/system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java#L127)), but multiple messages are correctly sent (I tried to raise the expected value on line 127 to 2 or 3... and test still passes).

> One possible solution to this bug is to remove the "Return Early" condition from the [TransferParts](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java#L51C20-L51C20) function. This will allow the HttpDataSink to process and transfer all partitions of data.

What is the "return early" condition? To get more insights on how the partitioning thing is working, please take a look at the superclass [`ParallelSink`](https://github.com/eclipse-edc/Connector/blob/bbfcbabd564cc4b4bc1d76a7691318203670a80f/core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSink.java#L42)

**Comment by drcgjung** [comment] 2023-10-16 09:11
@ndr-brt @git-masoud 

Could you please reopen/reformulate this bug?q

1. The bug should rather be titled "Multiple messages in one partition are not being transfered in Http Dataplane" and the description should say "The HttpDataSink component only transfers the first message of each partition."

2. Using a (lossy) E2E-Test to verify an integrity condition is maybe a difficult instrument, but anyway I patched the test so that it uses different partition sizes and outputs the produced Kafka messages versus the consumed Http messages. 

```
--- a/system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
+++ b/system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
@@ -79,6 +79,7 @@ class EndToEndKafkaTransferTest {
     private static final int EVENT_DESTINATION_PORT = getFreePort();
     private static final JsonNode JSON_MESSAGE = sampleMessage();
     private static final AtomicInteger MESSAGE_COUNTER = new AtomicInteger();
+    private static final AtomicInteger RECEPTION_COUNTER = new AtomicInteger();
 
     private static final EndToEndTransferParticipant CONSUMER = EndToEndTransferParticipant.Builder.newInstance()
             .name("consumer")
@@ -122,7 +123,8 @@ class EndToEndKafkaTransferTest {
                 .withMethod(HttpMethod.POST.name())
                 .withPath(SINK_HTTP_PATH)
                 .withBody(OBJECT_MAPPER.writeValueAsBytes(JSON_MESSAGE));
-        destinationServer.when(request).respond(response());
+        var resp = response();
+        destinationServer.when(request).respond( (req) -> { RECEPTION_COUNTER.incrementAndGet(); return resp; });
         PROVIDER.registerDataPlane(Set.of("Kafka"), Set.of("HttpData"));
 
         var assetId = UUID.randomUUID().toString();
@@ -146,6 +148,8 @@ class EndToEndKafkaTransferTest {
         });
 
         stopQuietly(destinationServer);
+
+        System.err.printf("Sent messages %d - received messages %d", MESSAGE_COUNTER.get(), RECEPTION_COUNTER.get());
     }
 
     @Test
```

```
--- a/system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
+++ b/system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
@@ -238,6 +238,7 @@ public class EndToEndTransferParticipant extends Participant {
                 put("edc.keystore", resourceAbsolutePath("certs/cert.pfx"));
                 put("edc.keystore.password", "123456");
                 put("edc.dataplane.token.validation.endpoint", controlPlaneControl + "/token");
+                put("edc.dataplane.http.sink.partition.size", "1");
             }
         };
     }
```

This is what I got running on my Mac M1 with debugger attached.

| Partition Size | Sent messages | Received messages |
| -------------- | ------------- | ----------------- |
| 1 | 313 | 46 |
| 2 | 333 | 19 |
| 3 | 384 | 14 |
| 4 | 349 | 8  |
| 5 (default) | 347 | 7  |
| 8 | 345 | 5  |

3. This should demonstrate that simply increasing the atLeast(1) test will not correctly reproduce the problematic behaviour of HttpSink. This should also demonstrate that the partition.size has an influence on the number of transferred messages via HttpSink - so it behaves indeed rather as a "sampleDistance" with a maximum at "1" - sampling every message the datasource produces. In my eyes, the partition.size of the (Parallel)Sink should not have an influence on the number of transferred messages.

If you share this view, please reopen this issue, give me a ping and we will provide a fix PR including a reproducing unit test.

**Comment by ndr-brt** [comment] 2023-10-16 09:29
@drcgjung the issue is still open, it just has a `stale` label attached because it stand with no interactions for 14 days.
A PR will be appreciated

**Closed** 2023-10-19 14:00 UTC
Labels: bug_report, triage
