### ISSUE TITLE
dsp: support transfer suspension

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3375] opened 2023-08-18 07:32 UTC
# Feature Request

Currently the Connector is not able to dispatch and receive the [`TransferSuspensionMessage`](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/transfer-process/transfer.process.protocol#3.-transfersuspensionmessage).

The feature should permit to from a consumer or provider perspective a way to suspend/resume a `TransferProcess` through a Management API call, so there will be needed:
- management api endpoints
- `TransferProcessService` methods
- `TransferSuspensionMessage` dispatch/reception
- a state machine processor that notifies the data-plane in case of suspension/recovery

## Which Areas Would Be Affected?

core

## Why Is the Feature Desired?

dsp completion

**Comment by paullatzelsperger** [comment] 2023-09-13 08:38
duplicate of #3350

**Closed by paullatzelsperger** 2023-09-13 08:38 UTC
Labels: duplicate, enhancement, dataspace-protocol
