### ISSUE TITLE
Getting error while running Connector when I include decentralized-identity extension in my project

### ISSUE THREAD

**Issue by MUsman1992** [eclipse-edc/Connector#3020] opened 2023-05-16 11:04 UTC
I am using decentralized-identity extension https://github.com/eclipse-edc/Connector/tree/main/extensions/common/iam/decentralized-identity for development purposes. When I try to build the project, I get this error:

```
SEVERE 2023-05-16T12:13:51.1763427 Error booting runtime: The following injected fields were not provided: Field "credentialsVerifier" of type [interface org.eclipse.edc.iam.did.spi.credentials.CredentialsVerifier] required by org.eclipse.edc.iam.did.service.DecentralizedIdentityServiceExtension
org.eclipse.edc.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "credentialsVerifier" of type [interface org.eclipse.edc.iam.did.spi.credentials.CredentialsVerifier] required by org.eclipse.edc.iam.did.service.DecentralizedIdentityServiceExtension
	at org.eclipse.edc.boot.system.DependencyGraph.of(DependencyGraph.java:102)
	at org.eclipse.edc.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:119)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:162)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:221)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:87)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:75)
Disconnected from the target VM, address: '127.0.0.1:53507', transport: 'socket'

Process finished with exit code -1

```

I know from documentation that this module is currently under development but I just want to use it for a small demo purpose to give audience an idea what I have investigated for implementing decentralized-identity. Can anyone guide me how to run the code that has been yet developed. Is it a bug or am I doing something wrong because I also could not find any implementation of the CredentialsVerifier class in the Connector project.

**Comment by paullatzelsperger** [comment] 2023-07-05 08:33
Hey @MUsman1992, you need to implement and register a `CredentialsVerifier`, for example you could look at [this one provided by IdentityHub](https://github.com/eclipse-edc/IdentityHub/blob/main/core/identity-hub-credentials-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/IdentityHubCredentialsVerifier.java). Closing, because its not a bug.

**Closed by paullatzelsperger** 2023-07-05 08:33 UTC
Labels: bug_report, triage
